
DROP VIEW  IF EXISTS vw_multa;
DROP TABLE IF EXISTS pagamento, multa, locacao_exemplar, locacao,
                     reserva_exemplar, reserva, exemplar, filme_diretor,
                     filme_genero, filme, diretor, genero, estudio,
                     funcionario, telefone_cliente, cliente, endereco,
                     cidade, estado CASCADE;

CREATE TABLE estado (
    id_estado   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(50) NOT NULL,
    sigla       CHAR(2)     NOT NULL UNIQUE
);

CREATE TABLE cidade (
    id_cidade   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL,
    id_estado   INT NOT NULL REFERENCES estado (id_estado)
);

CREATE TABLE endereco (
    id_endereco INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rua         VARCHAR(150) NOT NULL,
    nr_casa     VARCHAR(10)  NOT NULL,
    bairro      VARCHAR(100) NOT NULL,
    cep         CHAR(8)      NOT NULL CHECK (cep ~ '^[0-9]{8}$'),
    id_cidade   INT NOT NULL REFERENCES cidade (id_cidade)
);

CREATE TABLE cliente (
    id_cliente    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome          VARCHAR(100) NOT NULL,
    cpf           CHAR(11)     NOT NULL UNIQUE CHECK (cpf ~ '^[0-9]{11}$'),
    email         VARCHAR(100),
    dt_nascimento DATE         NOT NULL,
    id_endereco   INT NOT NULL REFERENCES endereco (id_endereco)
);

CREATE TABLE telefone_cliente (
    id_cliente  INT NOT NULL REFERENCES cliente (id_cliente) ON DELETE CASCADE,
    telefone    VARCHAR(15) NOT NULL,
    PRIMARY KEY (id_cliente, telefone)
);

CREATE TABLE funcionario (
    id_funcionario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome           VARCHAR(100) NOT NULL,
    cpf            CHAR(11)     NOT NULL UNIQUE CHECK (cpf ~ '^[0-9]{11}$'),
    cargo          VARCHAR(50)  NOT NULL
);

CREATE TABLE estudio (
    id_estudio  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE genero (
    id_genero   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE diretor (
    id_diretor  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome        VARCHAR(100) NOT NULL
);

CREATE TABLE filme (
    id_filme            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo              VARCHAR(150) NOT NULL,
    ano_lancamento      INT NOT NULL,
    duracao_minutos     INT NOT NULL CHECK (duracao_minutos > 0),
    classificacao_idade INT NOT NULL CHECK (classificacao_idade IN (0, 10, 12, 14, 16, 18)),
    id_estudio          INT NOT NULL REFERENCES estudio (id_estudio)
);

CREATE TABLE filme_genero (
    id_filme    INT NOT NULL REFERENCES filme (id_filme) ON DELETE CASCADE,
    id_genero   INT NOT NULL REFERENCES genero (id_genero),
    PRIMARY KEY (id_filme, id_genero)
);

CREATE TABLE filme_diretor (
    id_filme    INT NOT NULL REFERENCES filme (id_filme) ON DELETE CASCADE,
    id_diretor  INT NOT NULL REFERENCES diretor (id_diretor),
    PRIMARY KEY (id_filme, id_diretor)
);

CREATE TABLE exemplar (
    id_exemplar INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_midia  VARCHAR(10) NOT NULL CHECK (tipo_midia IN ('DVD', 'Blu-Ray', '4K')),
    status      VARCHAR(15) NOT NULL DEFAULT 'disponivel'
                CHECK (status IN ('disponivel', 'locado', 'danificado')),
    id_filme    INT NOT NULL REFERENCES filme (id_filme)
);

CREATE TABLE reserva (
    id_reserva  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_reserva  TIMESTAMP   NOT NULL DEFAULT now(),
    status      VARCHAR(10) NOT NULL DEFAULT 'ativa'
                CHECK (status IN ('ativa', 'atendida', 'cancelada', 'expirada')),
    id_cliente  INT NOT NULL REFERENCES cliente (id_cliente)
);

CREATE TABLE reserva_exemplar (
    id_reserva  INT NOT NULL REFERENCES reserva (id_reserva) ON DELETE CASCADE,
    id_exemplar INT NOT NULL REFERENCES exemplar (id_exemplar),
    PRIMARY KEY (id_reserva, id_exemplar)
);

CREATE TABLE locacao (
    id_locacao            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dt_locacao            TIMESTAMP     NOT NULL DEFAULT now(),
    dt_prevista_devolucao DATE          NOT NULL,
    valor                 NUMERIC(10,2) NOT NULL CHECK (valor >= 0),
    status                VARCHAR(12)   NOT NULL DEFAULT 'em andamento'
                          CHECK (status IN ('em andamento', 'atrasada', 'encerrada')),
    id_cliente            INT NOT NULL REFERENCES cliente (id_cliente),
    id_funcionario        INT NOT NULL REFERENCES funcionario (id_funcionario),
    CHECK (dt_prevista_devolucao BETWEEN dt_locacao::date AND dt_locacao::date + 30)
);

CREATE TABLE locacao_exemplar (
    id_locacao   INT NOT NULL REFERENCES locacao (id_locacao) ON DELETE CASCADE,
    id_exemplar  INT NOT NULL REFERENCES exemplar (id_exemplar),
    dt_devolucao TIMESTAMP,
    PRIMARY KEY (id_locacao, id_exemplar)
);

CREATE TABLE multa (
    id_multa      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor_diario  NUMERIC(10,2) NOT NULL CHECK (valor_diario > 0),
    dt_vencimento DATE          NOT NULL,
    status        VARCHAR(10)   NOT NULL DEFAULT 'pendente'
                  CHECK (status IN ('pendente', 'paga')),
    id_locacao    INT NOT NULL UNIQUE REFERENCES locacao (id_locacao)
);

CREATE TABLE pagamento (
    id_pagamento    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    valor           NUMERIC(10,2) NOT NULL CHECK (valor > 0),
    dt_pagamento    TIMESTAMP     NOT NULL DEFAULT now(),
    forma_pagamento VARCHAR(10)   NOT NULL
                    CHECK (forma_pagamento IN ('dinheiro', 'debito', 'credito', 'pix')),
    id_funcionario  INT NOT NULL REFERENCES funcionario (id_funcionario),
    id_locacao      INT UNIQUE REFERENCES locacao (id_locacao),
    id_multa        INT UNIQUE REFERENCES multa (id_multa),
    CHECK ((id_locacao IS NULL) <> (id_multa IS NULL))
);

CREATE VIEW vw_multa AS
SELECT m.id_multa,
       m.id_locacao,
       GREATEST(0, MAX(le.dt_devolucao)::date - l.dt_prevista_devolucao)                  AS dias_atraso,
       GREATEST(0, MAX(le.dt_devolucao)::date - l.dt_prevista_devolucao) * m.valor_diario AS valor_total
FROM multa m
JOIN locacao l           ON l.id_locacao  = m.id_locacao
JOIN locacao_exemplar le ON le.id_locacao = l.id_locacao
GROUP BY m.id_multa, m.id_locacao, l.dt_prevista_devolucao, m.valor_diario;

INSERT INTO estado (id_estado, nome, sigla) VALUES
 (1, 'Santa Catarina', 'SC'),
 (2, 'Paraná', 'PR'),
 (3, 'Rio Grande do Sul', 'RS'),
 (4, 'São Paulo', 'SP'),
 (5, 'Rio de Janeiro', 'RJ');

INSERT INTO cidade (id_cidade, nome, id_estado) VALUES
 (1, 'Florianópolis', 1),
 (2, 'Blumenau', 1),
 (3, 'Itajaí', 1),
 (4, 'Curitiba', 2),
 (5, 'Londrina', 2),
 (6, 'Porto Alegre', 3),
 (7, 'São Paulo', 4),
 (8, 'Rio de Janeiro', 5);

INSERT INTO endereco (id_endereco, rua, nr_casa, bairro, cep, id_cidade) VALUES
 (1, 'Rua das Palmeiras', '120', 'Centro', '88010100', 1),
 (2, 'Avenida Beira-Mar', '1580', 'Agronômica', '88025300', 1),
 (3, 'Rua XV de Novembro', '455', 'Centro', '89010001', 2),
 (4, 'Rua Brusque', '87', 'Vila Operária', '88303001', 3),
 (5, 'Rua Marechal Deodoro', '910', 'Centro', '80020320', 4),
 (6, 'Avenida Higienópolis', '33', 'Centro', '86020080', 5),
 (7, 'Rua dos Andradas', '1001', 'Centro Histórico', '90020007', 6),
 (8, 'Rua Augusta', '2200', 'Consolação', '01412100', 7),
 (9, 'Rua Voluntários da Pátria', '78', 'Botafogo', '22270010', 8);

INSERT INTO cliente (id_cliente, nome, cpf, email, dt_nascimento, id_endereco) VALUES
 (1,  'Ana Paula Souza',         '52601815906', 'ana.souza@email.com',      '1990-03-14', 1),
 (2,  'Bruno Carvalho Lima',     '08301661305', 'bruno.lima@email.com',     '1985-11-02', 2),
 (3,  'Carla Mendes Rocha',      '18609139034', 'carla.rocha@email.com',    '1998-07-21', 3),
 (4,  'Diego Fernandes Alves',   '99603082430', 'diego.alves@email.com',    '2001-01-30', 4),
 (5,  'Eduarda Martins Costa',   '62819482112', 'eduarda.costa@email.com',  '1979-05-09', 5),
 (6,  'Felipe Ribeiro Santos',   '99351819019', 'felipe.santos@email.com',  '1995-09-17', 6),
 (7,  'Gabriela Nunes Pereira',  '93786579741', 'gabi.nunes@email.com',     '1988-12-25', 7),
 (8,  'Henrique Oliveira Dias',  '54323194897', NULL,                       '1972-04-03', 8),
 (9,  'Isabela Moura Teixeira',  '75749118606', 'isabela.moura@email.com',  '2003-08-11', 9),
 (10, 'Lucas Moura Teixeira',    '25276018987', NULL, (CURRENT_DATE - INTERVAL '15 years 2 months')::date, 9);

INSERT INTO telefone_cliente (id_cliente, telefone) VALUES
 (1, '48991234567'), (1, '4832223344'),
 (2, '48998765432'),
 (3, '47991112233'),
 (4, '47988776655'),
 (5, '41999887766'), (5, '4133445566'),
 (6, '43991234001'),
 (7, '51998001122'),
 (8, '11987654321'),
 (9, '21991230000'),
 (10, '21991230001');

INSERT INTO funcionario (id_funcionario, nome, cpf, cargo) VALUES
 (1, 'Marcos Vinícius Prado',  '55597971115', 'Gerente'),
 (2, 'Juliana Castro Freitas', '47104974601', 'Atendente'),
 (3, 'Rafael Almeida Borges',  '50752917080', 'Atendente'),
 (4, 'Patrícia Gomes Lopes',   '34236671255', 'Caixa');

INSERT INTO estudio (id_estudio, nome) VALUES
 (1, 'Warner Bros. Pictures'),
 (2, 'Universal Pictures'),
 (3, 'Paramount Pictures'),
 (4, '20th Century Studios'),
 (5, 'Miramax'),
 (6, 'Pixar Animation Studios'),
 (7, 'A24'),
 (8, 'Columbia Pictures');

INSERT INTO genero (id_genero, nome) VALUES
 (1, 'Ação'), (2, 'Aventura'), (3, 'Comédia'), (4, 'Drama'),
 (5, 'Ficção Científica'), (6, 'Terror'), (7, 'Suspense'), (8, 'Animação'),
 (9, 'Romance'), (10, 'Fantasia'), (11, 'Crime');

INSERT INTO diretor (id_diretor, nome) VALUES
 (1, 'Christopher Nolan'), (2, 'Steven Spielberg'), (3, 'Denis Villeneuve'),
 (4, 'Quentin Tarantino'), (5, 'Martin Scorsese'), (6, 'Ridley Scott'),
 (7, 'James Cameron'), (8, 'Greta Gerwig'), (9, 'Jordan Peele'),
 (10, 'John Lasseter'), (11, 'Lana Wachowski'), (12, 'Lilly Wachowski'),
 (13, 'Daniel Kwan'), (14, 'Daniel Scheinert');

INSERT INTO filme (id_filme, titulo, ano_lancamento, duracao_minutos, classificacao_idade, id_estudio) VALUES
 (1,  'A Origem', 2010, 148, 14, 1),
 (2,  'Interestelar', 2014, 169, 10, 3),
 (3,  'Jurassic Park', 1993, 127, 12, 2),
 (4,  'Duna', 2021, 155, 14, 1),
 (5,  'Pulp Fiction', 1994, 154, 18, 5),
 (6,  'O Lobo de Wall Street', 2013, 180, 18, 3),
 (7,  'Gladiador', 2000, 155, 14, 2),
 (8,  'Titanic', 1997, 194, 12, 4),
 (9,  'Avatar', 2009, 162, 12, 4),
 (10, 'Barbie', 2023, 114, 12, 1),
 (11, 'Corra!', 2017, 104, 16, 2),
 (12, 'Oppenheimer', 2023, 180, 16, 2),
 (13, 'Toy Story', 1995, 81, 0, 6),
 (14, 'Matrix', 1999, 136, 14, 1),
 (15, 'Kill Bill: Volume 1', 2003, 111, 18, 5),
 (16, 'Tudo em Todo o Lugar ao Mesmo Tempo', 2022, 139, 14, 7);

INSERT INTO filme_genero (id_filme, id_genero) VALUES
 (1, 1), (1, 5), (1, 7),
 (2, 4), (2, 5),
 (3, 2), (3, 5),
 (4, 2), (4, 5),
 (5, 11), (5, 4),
 (6, 3), (6, 4),
 (7, 1), (7, 4),
 (8, 4), (8, 9),
 (9, 2), (9, 5),
 (10, 3), (10, 10),
 (11, 6), (11, 7),
 (12, 4),
 (13, 8), (13, 3),
 (14, 1), (14, 5),
 (15, 1), (15, 11),
 (16, 1), (16, 3), (16, 5);

INSERT INTO filme_diretor (id_filme, id_diretor) VALUES
 (1, 1), (2, 1), (3, 2), (4, 3), (5, 4), (6, 5), (7, 6), (8, 7),
 (9, 7), (10, 8), (11, 9), (12, 1), (13, 10), (14, 11), (14, 12),
 (15, 4), (16, 13), (16, 14);

INSERT INTO exemplar (id_exemplar, tipo_midia, status, id_filme) VALUES
 (1,  'DVD',     'disponivel', 1),
 (2,  'Blu-Ray', 'disponivel', 1),
 (3,  '4K',      'disponivel', 1),
 (4,  'DVD',     'disponivel', 2),
 (5,  'Blu-Ray', 'disponivel', 2),
 (6,  'DVD',     'disponivel', 3),
 (7,  'Blu-Ray', 'disponivel', 3),
 (8,  'Blu-Ray', 'disponivel', 4),
 (9,  '4K',      'disponivel', 4),
 (10, 'DVD',     'disponivel', 5),
 (11, 'DVD',     'disponivel', 6),
 (12, 'Blu-Ray', 'disponivel', 6),
 (13, 'DVD',     'disponivel', 7),
 (14, 'Blu-Ray', 'locado',     7),
 (15, 'DVD',     'locado',     8),
 (16, 'Blu-Ray', 'disponivel', 8),
 (17, 'Blu-Ray', 'locado',     9),
 (18, '4K',      'disponivel', 9),
 (19, 'DVD',     'disponivel', 10),
 (20, 'Blu-Ray', 'disponivel', 10),
 (21, 'DVD',     'disponivel', 11),
 (22, 'Blu-Ray', 'disponivel', 12),
 (23, '4K',      'locado',     12),
 (24, 'DVD',     'disponivel', 13),
 (25, 'DVD',     'danificado', 13),
 (26, 'DVD',     'disponivel', 14),
 (27, 'Blu-Ray', 'locado',     14),
 (28, 'DVD',     'locado',     15),
 (29, 'Blu-Ray', 'disponivel', 16);

INSERT INTO reserva (id_reserva, dt_reserva, status, id_cliente) VALUES
 (1, now() - INTERVAL '2 days',  'ativa',     9),
 (2, now() - INTERVAL '30 days', 'expirada',  4),
 (3, now() - INTERVAL '5 days',  'atendida',  1),
 (4, now() - INTERVAL '10 days', 'cancelada', 6),
 (5, now() - INTERVAL '1 day',   'ativa',     7);

INSERT INTO reserva_exemplar (id_reserva, id_exemplar) VALUES
 (1, 5), (1, 18),
 (2, 9),
 (3, 23),
 (4, 12),
 (5, 29);

INSERT INTO locacao (id_locacao, dt_locacao, dt_prevista_devolucao, valor, status, id_cliente, id_funcionario) VALUES
 (1,  now() - INTERVAL '60 days', CURRENT_DATE - 57, 8.00,  'encerrada',    1, 2),
 (2,  now() - INTERVAL '50 days', CURRENT_DATE - 47, 10.00, 'encerrada',    2, 3),
 (3,  now() - INTERVAL '40 days', CURRENT_DATE - 35, 8.00,  'encerrada',    3, 2),
 (4,  now() - INTERVAL '35 days', CURRENT_DATE - 30, 12.00, 'encerrada',    4, 3),
 (5,  now() - INTERVAL '20 days', CURRENT_DATE - 13, 10.00, 'atrasada',     5, 2),
 (6,  now() - INTERVAL '5 days',  CURRENT_DATE + 2,  12.00, 'em andamento', 6, 3),
 (7,  now() - INTERVAL '2 days',  CURRENT_DATE + 5,  8.00,  'em andamento', 1, 2),
 (8,  now() - INTERVAL '25 days', CURRENT_DATE - 22, 12.00, 'encerrada',    7, 3),
 (9,  now() - INTERVAL '15 days', CURRENT_DATE - 12, 10.00, 'encerrada',    2, 2),
 (10, now() - INTERVAL '10 days', CURRENT_DATE - 3,  8.00,  'atrasada',     8, 3),
 (11, now() - INTERVAL '12 days', CURRENT_DATE - 9,  4.00,  'encerrada',   10, 2);

INSERT INTO locacao_exemplar (id_locacao, id_exemplar, dt_devolucao) VALUES
 (1, 1,  now() - INTERVAL '56 days'), (1, 4,  now() - INTERVAL '56 days'),
 (2, 22, now() - INTERVAL '43 days'), (2, 13, now() - INTERVAL '43 days'),
 (3, 19, now() - INTERVAL '30 days'), (3, 24, now() - INTERVAL '30 days'),
 (4, 2,  now() - INTERVAL '31 days'), (4, 8,  now() - INTERVAL '31 days'),
 (5, 6,  now() - INTERVAL '15 days'), (5, 17, NULL),
 (6, 14, NULL), (6, 27, NULL),
 (7, 23, NULL),
 (8, 3,  now() - INTERVAL '24 days'), (8, 11, now() - INTERVAL '24 days'),
 (9, 20, now() - INTERVAL '9 days'),  (9, 26, now() - INTERVAL '9 days'),
 (10, 28, NULL), (10, 15, NULL),
 (11, 24, now() - INTERVAL '10 days');

INSERT INTO multa (id_multa, valor_diario, dt_vencimento, status, id_locacao) VALUES
 (1, 2.50, CURRENT_DATE - 33, 'paga',     2),
 (2, 2.50, CURRENT_DATE - 20, 'pendente', 3),
 (3, 2.50, CURRENT_DATE + 1,  'pendente', 9);

INSERT INTO pagamento (id_pagamento, valor, dt_pagamento, forma_pagamento, id_funcionario, id_locacao, id_multa) VALUES
 (1,  8.00,  now() - INTERVAL '60 days', 'dinheiro', 4, 1,    NULL),
 (2,  10.00, now() - INTERVAL '50 days', 'pix',      4, 2,    NULL),
 (3,  10.00, now() - INTERVAL '40 days', 'credito',  4, NULL, 1),
 (4,  8.00,  now() - INTERVAL '40 days', 'debito',   2, 3,    NULL),
 (5,  12.00, now() - INTERVAL '35 days', 'pix',      3, 4,    NULL),
 (6,  10.00, now() - INTERVAL '20 days', 'dinheiro', 2, 5,    NULL),
 (7,  8.00,  now() - INTERVAL '2 days',  'pix',      2, 7,    NULL),
 (8,  12.00, now() - INTERVAL '25 days', 'credito',  4, 8,    NULL),
 (9,  10.00, now() - INTERVAL '15 days', 'pix',      3, 9,    NULL),
 (10, 4.00,  now() - INTERVAL '12 days', 'dinheiro', 2, 11,   NULL);

SELECT setval(pg_get_serial_sequence('estado', 'id_estado'),           (SELECT MAX(id_estado) FROM estado));
SELECT setval(pg_get_serial_sequence('cidade', 'id_cidade'),           (SELECT MAX(id_cidade) FROM cidade));
SELECT setval(pg_get_serial_sequence('endereco', 'id_endereco'),       (SELECT MAX(id_endereco) FROM endereco));
SELECT setval(pg_get_serial_sequence('cliente', 'id_cliente'),         (SELECT MAX(id_cliente) FROM cliente));
SELECT setval(pg_get_serial_sequence('funcionario', 'id_funcionario'), (SELECT MAX(id_funcionario) FROM funcionario));
SELECT setval(pg_get_serial_sequence('estudio', 'id_estudio'),         (SELECT MAX(id_estudio) FROM estudio));
SELECT setval(pg_get_serial_sequence('genero', 'id_genero'),           (SELECT MAX(id_genero) FROM genero));
SELECT setval(pg_get_serial_sequence('diretor', 'id_diretor'),         (SELECT MAX(id_diretor) FROM diretor));
SELECT setval(pg_get_serial_sequence('filme', 'id_filme'),             (SELECT MAX(id_filme) FROM filme));
SELECT setval(pg_get_serial_sequence('exemplar', 'id_exemplar'),       (SELECT MAX(id_exemplar) FROM exemplar));
SELECT setval(pg_get_serial_sequence('reserva', 'id_reserva'),         (SELECT MAX(id_reserva) FROM reserva));
SELECT setval(pg_get_serial_sequence('locacao', 'id_locacao'),         (SELECT MAX(id_locacao) FROM locacao));
SELECT setval(pg_get_serial_sequence('multa', 'id_multa'),             (SELECT MAX(id_multa) FROM multa));
SELECT setval(pg_get_serial_sequence('pagamento', 'id_pagamento'),     (SELECT MAX(id_pagamento) FROM pagamento));
